import { useState } from 'react'
import { projects, skillGroups, workflow } from './data'
import profileImage from './assets/leh.jpeg'
import './App.css'

function App() {
  const [language, setLanguage] = useState<'en' | 'fr'>('en')
  const isFrench = language === 'fr'
  const text = isFrench ? {
    navWork: 'Projets', navJourney: 'Parcours', navContact: 'Contact', availability: 'Ouvert aux échanges',
    eyebrow: 'Développeur d’applications / En formation', heroTitle: <>Construire des choses utiles<br /><em>en apprenant.</em></>,
    heroCopy: 'Je suis Hamadoun Oumarou Sidibe, développeur d’applications en formation Full-Stack. Je conçois, déploie et améliore continuellement des applications web et mobiles.', view: 'Voir mes projets', talk: 'Parlons-en',
    about: '01 / À propos', aboutTitle: <>Encore en apprentissage.<br /><em>Déjà dans la pratique.</em></>, aboutCopy: 'J’étudie l’informatique et je suis actuellement une formation orientée Full-Stack. J’apprends surtout en construisant : des applications web, des prototypes mobiles et des projets pratiques qui doivent fonctionner au-delà de mon ordinateur.', aboutCopy2: 'Mon objectif est de créer des applications utiles, de comprendre comment elles sont conçues et d’améliorer mes choix techniques un par un.', journeyLink: 'Voir mon parcours technique',
    work: '02 / Projets sélectionnés', workNote: 'Des projets qui répondent à un besoin.', caseTitle: 'ColiReceipt / En détail', problem: 'Le problème', built: 'Ce que j’ai construit', learned: 'Ce que j’ai appris',
    journey: '03 / Parcours technique', journeyNote: 'Pas de pourcentages. Un état des lieux honnête.', currently: 'En approfondissement', process: '04 / Ma façon de construire', processNote: 'L’IA fait partie du processus, pas de mon identité.',
    contact: '05 / Me contacter', contactTitle: <>Construisons et<br /><em>apprenons ensemble.</em></>, contactCopy: 'Je suis ouvert aux opportunités, collaborations et environnements où je peux continuer à apprendre tout en contribuant à des projets utiles.', start: 'Démarrer une conversation',
  } : {
    navWork: 'Work', navJourney: 'Journey', navContact: 'Contact', availability: 'Open to conversations', eyebrow: 'Application developer / In training', heroTitle: <>Building useful things<br /><em>while learning.</em></>, heroCopy: 'I am Hamadoun Oumarou Sidibe, an application developer in full-stack training. I build, deploy and continuously improve web and mobile applications.', view: 'View my projects', talk: "Let's talk", about: '01 / About', aboutTitle: <>Still learning.<br /><em>Already building.</em></>, aboutCopy: 'I am studying computer science and currently training in full-stack development. I learn mostly by making: web applications, mobile prototypes and practical projects that have to work beyond my laptop.', aboutCopy2: 'My focus is on creating useful applications, understanding how they are put together and improving one technical decision at a time.', journeyLink: 'See my technical journey', work: '02 / Selected work', workNote: 'Projects with a reason to exist.', caseTitle: 'ColiReceipt / A closer look', problem: 'The problem', built: 'What I built', learned: 'What it taught me', journey: '03 / Technical journey', journeyNote: 'No percentages. Just an honest snapshot.', currently: 'Currently deepening', process: '04 / How I build', processNote: 'AI is part of the workflow, not the identity.', contact: "05 / Let's connect", contactTitle: <>Let's build and<br /><em>learn together.</em></>, contactCopy: 'I am open to opportunities, collaborations and environments where I can keep learning while contributing to useful work.', start: 'Start a conversation'
  }
  const localizedProjects = isFrench ? projects.map((project) => project.name === 'ColiReceipt' ? { ...project, label: 'Projet principal / Application déployée', description: 'Une application de gestion de colis conçue pour gérer les envois, clients, paiements, trajets et utilisateurs.' } : { ...project, label: 'Projet académique / Prototype', description: 'Un concept de covoiturage et de moto-partage pour la mobilité scolaire, exploré dans le cadre d’un projet académique.' }) : projects
  return (
    <main>
      <nav className="nav" aria-label="Main navigation">
        <a className="wordmark" href="#top">HOS<span>.</span></a>
        <div className="nav-links">
          <a href="#work">{text.navWork}</a><a href="#journey">{text.navJourney}</a><a href="#contact">{text.navContact}</a>
        </div>
        <div className="nav-tools"><button className="language-toggle" type="button" onClick={() => setLanguage(isFrench ? 'en' : 'fr')} aria-label="Change language">{isFrench ? 'EN' : 'FR'}</button><a className="availability" href="mailto:sidibehamadounumar@gmail.com"><span /> {text.availability}</a></div>
      </nav>
      <section className="hero" id="top">
        <p className="eyebrow">{text.eyebrow}</p><h1>{text.heroTitle}</h1>
        <div className="hero-bottom"><p className="hero-copy">{text.heroCopy}</p><div className="hero-actions"><a className="button button-primary" href="#work">{text.view} <span>↘</span></a><a className="button button-quiet" href="mailto:sidibehamadounumar@gmail.com">{text.talk} <span>↗</span></a></div></div>
        <div className="hero-mark" aria-hidden="true">HOS<span>/</span>26</div><img className="profile-image" src={profileImage} alt="Portrait of Hamadoun Oumarou Sidibe" />
      </section>
      <section className="intro section-rule"><p className="section-index">{text.about}</p><div className="intro-content"><h2>{text.aboutTitle}</h2><div className="intro-text"><p>{text.aboutCopy}</p><p>{text.aboutCopy2}</p><a className="text-link" href="#journey">{text.journeyLink} <span>↘</span></a></div></div></section>
      <section className="work section-rule" id="work"><div className="section-heading"><p className="section-index">{text.work}</p><p className="section-note">{text.workNote}</p></div><div className="project-list">{localizedProjects.map((project) => <article className={`project ${project.featured ? 'project-featured' : ''}`} key={project.name}><div className="project-number">{project.number}</div><div className="project-main"><p className="project-label">{project.label}</p><h2>{project.name}</h2><p className="project-description">{project.description}</p><div className="tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="project-arrow" aria-hidden="true">↗</div></article>)}</div><div className="case-study"><p className="section-index">{text.caseTitle}</p><div className="case-grid"><div><h3>{text.problem}</h3><p>{isFrench ? 'Les opérations de colis ont besoin d’un moyen plus clair de suivre les envois, paiements, trajets, agents et clients au même endroit.' : 'Parcel operations need a clearer way to follow shipments, payments, trips, agents and clients in one place.'}</p></div><div><h3>{text.built}</h3><p>{isFrench ? 'Une application de gestion responsive avec authentification, rôles, tableaux de bord, rapports et données capables de fonctionner hors ligne puis de se synchroniser.' : 'A responsive management application with authentication, roles, dashboards, reports and data that can keep working offline and sync later.'}</p></div><div><h3>{text.learned}</h3><p>{isFrench ? 'Les API, Prisma, PostgreSQL, le déploiement, la persistance, les erreurs réseau et le débogage quotidien derrière une vraie application.' : 'Working with APIs, Prisma, PostgreSQL, deployment, persistence, network errors and the everyday debugging behind a real application.'}</p></div></div></div></section>
      <section className="journey section-rule" id="journey"><div className="section-heading"><p className="section-index">03 / Technical journey</p><p className="section-note">No percentages. Just an honest snapshot.</p></div><div className="skills-grid">{skillGroups.map((group) => <div className={`skill-group ${group.tone}`} key={group.title}><h3>{group.title}</h3><div className="skill-list">{group.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div>)}</div><div className="learning-strip"><span>Currently deepening</span><p>Full-stack architecture <i>·</i> APIs <i>·</i> Databases <i>·</i> Authentication <i>·</i> Testing <i>·</i> Deployment</p></div></section>
      <section className="process section-rule"><div className="section-heading"><p className="section-index">04 / How I build</p><p className="section-note">AI is part of the workflow, not the identity.</p></div><div className="workflow">{workflow.map(([number, title, copy]) => <div className="workflow-step" key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
      <section className="contact section-rule" id="contact"><p className="section-index">05 / Let's connect</p><h2>Let's build and<br /><em>learn together.</em></h2><p className="contact-copy">I am open to opportunities, collaborations and environments where I can keep learning while contributing to useful work.</p><a className="button button-primary" href="mailto:sidibehamadounumar@gmail.com">Start a conversation <span>↗</span></a><div className="contact-links"><a href="https://github.com/rwandadream" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/hamadoun-o-sidibe" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="mailto:sidibehamadounumar@gmail.com">sidibehamadounumar@gmail.com ↗</a></div></section>
      <footer><span>Hamadoun Oumarou Sidibe</span><span>Application Developer · Full-Stack Developer in Training</span><span>© 2026</span></footer>
    </main>
  )
}

export default App
